# (PART) 数理基础 {-}

# 马尔可夫模型 {#MarkovModel}

本章只给出对马尔可夫链的通俗解释，适用于非专业、仅需稍微了解其背景的读者。

## 定义 {#MarkovModel-Defination}

### 马尔可夫性质 {#MarkovModel-Defination-Property}

用通俗的语言来说，马尔可夫性质指：事物在某一时刻处于某种状态时，在下一时刻转移/维持到任意可能状态的概率，仅取决于事物在这一时刻的状态。

### 马尔可夫过程 {#MarkovModel-Defination-Process}

理解了马尔可夫性质后，马尔可夫过程就很好理解了。它指的就是具有马尔可夫性质的随机过程。

### 马尔可夫链 {#MarkovModel-Defination-Chain}

马尔可夫链则是马尔可夫过程的子集，一般而言，当马尔可夫过程的时间和状态都是离散时，即是马尔可夫链。

### N阶马尔可夫链 {#MarkovModel-Defination-Chain-N}

N阶马尔可夫链上，事物转移/维持到任意可能状态的概率由前N个时刻的状态决定。

传统的马尔可夫链可以认为是1阶马尔可夫链。

### 马尔可夫模型 {#MarkovModel-Defination-Model}

以马尔可夫性质为基础的随机过程及随机模型的集合，例如马尔可夫链、隐马尔可夫模型。

### 隐马尔可夫模型 {#MarkovModel-Defination-Hidden}

当马尔可夫过程的状态不能被直接观察到，但能通过输出状态反解隐藏状态时，该马尔可夫过程被称为隐马尔可夫模型。

## 马尔可夫链的数学表示 {#MarkovModel-Math}

如果具有一定的网络概念基础，不难发现马尔可夫链的状态转移可以使用矩阵或图来表示。这分别称为转移矩阵和转移图。

::: {.rmdnote}
如果没有网络概念基础，此处给出一个简化的概念解释。

**网络的基本概念**

所谓网络，即是对具有联系的事物的抽象。“网络”是对这类事物及其间关系的总和的形象概括。想象日常生活中的蜘蛛网，上有若干长长的蛛丝，而每根蛛丝交界的地方就是一个点。而在“网络”概念中，那些**可能**有联系的事物的集合就是网络中的节点集合，而事物间的联系就是网络的边。

在马尔可夫链中，各个状态即可被视为网络中的节点，而状态间的转移，即是状态的联系，也就是网络中的边。

**网络的数学表示**

网络的数学表示有两种，一种是图，一种是矩阵。

图是数学分支图论中的核心概念，读者不必知道太多关于图的理论。只需知道，使用图来表示状态间的“网络”，其目的在于计算图论中关于图的一些特征，以计算马尔可夫链的特征。

相较于“图”，矩阵则更加便于计算。事实上，图和矩阵是可以相互转换的。一般而言，图向矩阵转换时，当点$i$与点$j$间有联系时，则记$a_{ij}=a_{ji}=1$。而当矩阵向图转换时，则反之。

使用矩阵的目的则是利用线性代数运算的便利性。例如，当矩阵$A$与矩阵$B$相乘时，记生成的矩阵为$C$，则$c_{ij}$表示$A$中的第$i$行和$B$中的第$j$列中的元素依次相乘并累加。那么，当矩阵$A$与矩阵$B$表示的是同一组对象（节点）间的关系$R_A$和$R_B$的存在时，则$c_{ij}$表示对象$i$和对象$j$通过1次关系$R_A$和1次关系$R_B$后能够产生关联的唯一路径数。特别地，如果矩阵$A$与矩阵$B$表示同一种关系，则$c_{ij}$表示对象$i$和对象$j$间距离为2的路径的总数。

注意，上述例子中的运算结果解释适用于01网络（Binary Network）。对于权重网络（Weighed Network），如果权重恒正时，则可以通过元$c_{ij}$是否大于0，来判断对象$i$和对象$j$是否有距离为2的路径。若权重有正有负，则该运算不能做上述解读。

对于不熟悉网络类型的读者，请往下看。

**网络的类型**

网络的分类主要基于图的分类，主要有以下维度：

- 边包含的节点数：
  - 二元网络：边连接2个点。
  - 超网络：边连接3个及以上点。
- 边的方向性：
  - 有向网络：例如出口贸易，$i$到$j$有出口，不代表$j$到$i$有出口。
  - 无向网络：例如贸易，若$i$与$j$有贸易往来，一定有$j$与$i$有贸易往来。
- 边是否同质：
  - 01网络：只考虑有没有。
  - 权重网络：例如路网，从$i$到$j$有路，从$j$到$k$有路，但距离不一定相等。

一般而言，我们讨论的都是二元网络，超网络较为复杂。
:::

### 转移概率 {#MarkovModel-Math-Probability}

转移概率不难理解，即是从一个状态转移到另一个状态的概率。

转移概率可分为单步转移概率和N步转移概率。由于马尔可夫性质，从某一状态经过N步转为另一状态的概率，在给定所有的单步转移概率及时间跨度时，是可以计算的。

### 转移矩阵 {#MarkovModel-Math-Matrix}

转移矩阵中，$a_{ij}$表示当状态为$s_i$时，下一时刻状态为$s_j$的概率。由于某一时刻上，对象处在所有可能状态的概率的总和为1，因此转移矩阵是一个行和为1的矩阵。

类似地，也可以定义N步转移矩阵。N步转移矩阵等价于N个单步转移矩阵相乘。

### 转移图 {#MarkovModel-Math-Graph}

在转移图中，节点表示状态，而边表示可以从一个状态转移到另一个状态，且其权重等于转移的单步转移概率。注意，转移图是一个有向权重图。
